export const bannerForm_initialValues = {
  type: "",
  title: "",
  newuser: "",
  group: "",
  subgroup: "",
  category: "",
  discount: "",
  expire: false,
  offerType: "",
  discountType: "",
  typecode: "",
  level: "",
  minamount: "",
  redeem: "",
  usagelimit: "",
  vouchers: "",
  bannerType: "",
  image: "",
  isDisabled: false,
  toDate: new Date("2021-01-01T00:00:00.000Z"),
  fromDate: new Date("2021-01-01T00:00:00.000Z"),
};
