const status = [{ name: "Accept" }, { name: "Reject" }];

const tableTitle = [
  {
    id: "date",
    label: "Date",
    maxWidth: "10%",
    align: "left",
  },
  {
    id: "orderno",
    label: "Order No",
    maxWidth: "10%",
    align: "left",
  },
  {
    id: "customername",
    label: "Customer Name",
    maxWidth: "15%",
    align: "left",
  },
  {
    id: "address",
    label: "Address",
    maxWidth: "15%",
    align: "left",
  },
  {
    id: "quantity",
    label: "Quantity",
    maxWidth: "10%",
    align: "center",
  },
  {
    id: "totalamount",
    label: "Total Amount",
    maxWidth: "10%",
    align: "left",
  },
  {
    id: "refundable",
    label: "Refundable",
    maxWidth: "10%",
    align: "left",
  },
  {
    id: "status",
    label: "Status",
    maxWidth: "15%",
    align: "left",
  },
  {
    id: "action",
    label: "Action",
    maxWidth: "5%",
    align: "center",
  },
];

const tablelist = [
  {
    date: "02-09-2021",
    orderno: "12345",
    customername: "Martin",
    address: "Los Vegas",
    quantity: "3",
    totalamount: "30000",
    refundable: "Yes",
    status: "Processing",
  },
  {
    date: "02-09-2021",
    orderno: "12345",
    customername: "John",
    address: "Los Angeles",
    quantity: "4",
    totalamount: "40000",
    refundable: "No",
    status: "Completed",
  },
  {
    date: "02-09-2021",
    orderno: "12345",
    customername: "Martin",
    address: "Los Vegas",
    quantity: "3",
    totalamount: "30000",
    refundable: "Yes",
    status: "Processing",
  },
  {
    date: "02-09-2021",
    orderno: "12345",
    customername: "Martin",
    address: "Los Vegas",
    quantity: "3",
    totalamount: "30000",
    refundable: "Yes",
    status: "Failed",
  },
  {
    date: "02-09-2021",
    orderno: "12345",
    customername: "Martin",
    address: "Los Vegas",
    quantity: "3",
    totalamount: "30000",
    refundable: "Yes",
    status: "Completed",
  },
  {
    date: "02-09-2021",
    orderno: "12345",
    customername: "Martin",
    address: "Los Vegas",
    quantity: "3",
    totalamount: "30000",
    refundable: "Yes",
    status: "Processing",
  },
  {
    date: "02-09-2021",
    orderno: "12345",
    customername: "Martin",
    address: "Los Vegas",
    quantity: "3",
    totalamount: "30000",
    refundable: "Yes",
    status: "Failed",
  },
  {
    date: "02-09-2021",
    orderno: "12345",
    customername: "Martin",
    address: "Los Vegas",
    quantity: "3",
    totalamount: "30000",
    refundable: "Yes",
    status: "Processing",
  },
];

const innerData = [
  {
    itemorderid: "ZB00001A",
    productname: "Kanubia Easy 7 Syn Yaki Prem",
    quantity: "4",
    price: "1000",
    totalamount: "4000",
    reason: "Color",
    trackingid: "ZBT001",
    status: "Processing",
  },
  {
    itemorderid: "ZB00001A",
    productname: "Kanubia Easy 7 Syn Yaki Prem",
    quantity: "4",
    price: "1000",
    totalamount: "4000",
    reason: "Color",
    trackingid: "ZBT001",
    status: "Completed",
  },
  {
    itemorderid: "ZB00001A",
    productname: "Kanubia Easy 7 Syn Yaki Prem",
    quantity: "4",
    price: "1000",
    totalamount: "4000",
    reason: "Color",
    trackingid: "ZBT001",
    status: "Failed",
  },
  {
    itemorderid: "ZB00001A",
    productname: "Kanubia Easy 7 Syn Yaki Prem",
    quantity: "4",
    price: "1000",
    totalamount: "4000",
    reason: "Color",
    trackingid: "ZBT001",
    status: "Failed",
  },
  {
    itemorderid: "ZB00001A",
    productname: "Kanubia Easy 7 Syn Yaki Prem",
    quantity: "4",
    price: "1000",
    totalamount: "4000",
    reason: "Color",
    trackingid: "ZBT001",
    status: "Processing",
  },
  {
    itemorderid: "ZB00001A",
    productname: "Kanubia Easy 7 Syn Yaki Prem",
    quantity: "4",
    price: "1000",
    totalamount: "4000",
    reason: "Color",
    trackingid: "ZBT001",
    status: "Failed",
  },
];

const condition = [
    {title: "Good"}, 
    {title: "Reject"}
]
export { status, tableTitle, tablelist, innerData, condition };
